BEGIN;
ALTER TABLE extract_logs ADD COLUMN IF NOT EXISTS raw_text_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE extract_logs ADD COLUMN IF NOT EXISTS claim_id TEXT NOT NULL DEFAULT '';
ALTER TABLE extract_logs ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT '';
ALTER TABLE extract_logs ADD COLUMN IF NOT EXISTS model_name TEXT NOT NULL DEFAULT '';
COMMIT;
