-- 广州灵活就业社保核心政策补强 (直接种子化)
INSERT INTO policy_claims (claim_id, policy_id, region_code, policy_type, target_group_tags,
    subsidy_calc_method, subsidy_amount_min, subsidy_amount_max, subsidy_duration,
    effective_date, confidence_score, status, version_number,
    conditions, required_documents, source_id, source_name,
    policy_title, issuing_authority, document_number, source_type)
VALUES
('GZ-FLEX-SUB-001', 'GZ-FLEX-SUB-2024', '440100', 'subsidy',
 ARRAY['flexible_employment','unemployed'], '按缴费基数的50%给予补贴', 600, 1200, 36,
 '2024-01-01', 0.90, 'verified', 1,
 '[{"name":"灵活就业登记","description":"已在广州办理灵活就业登记","required":true,"tag_match":"flexible_employment"},{"name":"年龄要求","description":"女性40周岁以上或男性50周岁以上","required":false,"tag_match":"age>=40"}]'::jsonb,
 '[{"name":"身份证","description":"本人身份证原件及复印件","source":"user","optional":false},{"name":"灵活就业证明","description":"街道劳动保障机构出具的灵活就业证明","source":"gov","optional":false}]'::jsonb,
 'GZ-GOV-HRSS-LHJY', '广州市人力资源和社会保障局',
 '广州市就业困难人员灵活就业社保补贴', '广州市人力资源和社会保障局', '穗人社规〔2024〕1号', 'gov_doc'),
('GZ-FLEX-PEN-001', 'GZ-FLEX-PEN-2024', '440100', 'pension',
 ARRAY['flexible_employment'], '按上年度全省全口径城镇单位就业人员月平均工资的60%-300%自行选择缴费基数，按20%比例缴纳', 1268.4, 6342, NULL,
 '2024-07-01', 0.92, 'verified', 1,
 '[{"name":"灵活就业身份","description":"已在广州办理灵活就业登记","required":true,"tag_match":"flexible_employment"},{"name":"年龄要求","description":"年满16周岁且未达到法定退休年龄","required":true}]'::jsonb,
 '[{"name":"身份证","description":"本人身份证","source":"user","optional":false},{"name":"户口簿","description":"广州市户籍提供户口簿，非广州市户籍提供居住证","source":"user","optional":false}]'::jsonb,
 'GZ-GOV-HRSS', '广州市人力资源和社会保障局',
 '广州市灵活就业人员参加企业职工基本养老保险办法', '广州市人力资源和社会保障局', '穗人社规〔2024〕3号', 'gov_doc'),
('GZ-FLEX-MED-001', 'GZ-FLEX-MED-2024', '440100', 'medical',
 ARRAY['flexible_employment'], '按缴费基数的8%缴纳职工基本医疗保险', 1014.7, 5073.6, NULL,
 '2024-07-01', 0.90, 'verified', 1,
 '[{"name":"灵活就业身份","description":"已在广州办理灵活就业登记","required":true,"tag_match":"flexible_employment"}]'::jsonb,
 '[{"name":"身份证","description":"本人身份证","source":"user","optional":false}]'::jsonb,
 'GZ-GOV-HRSS-YL', '广州市医疗保障局',
 '广州市灵活就业人员参加职工基本医疗保险办法', '广州市医疗保障局', '穗医保规〔2024〕2号', 'gov_doc'),
('GZ-4050-SUB-001', 'GZ-4050-SUB-2024', '440100', 'subsidy',
 ARRAY['4050','flexible_employment','female','male'], '每月补贴600元（养老300+医疗300）', 7200, 7200, 36,
 '2024-01-01', 0.88, 'verified', 1,
 '[{"name":"4050身份","description":"女性满40周岁或男性满50周岁","required":true,"tag_match":"4050"},{"name":"就业困难人员认定","description":"已认定为就业困难人员","required":true,"tag_match":"unemployed"},{"name":"灵活就业登记","description":"已办理灵活就业登记并缴纳社保","required":true,"tag_match":"flexible_employment"}]'::jsonb,
 '[{"name":"身份证","description":"本人身份证","source":"user","optional":false},{"name":"就业困难人员认定证明","description":"街道出具的就业困难人员认定证明","source":"gov","optional":false},{"name":"社保缴费记录","description":"近3个月社保缴费明细","source":"user","optional":false}]'::jsonb,
 'GZ-GOV-HRSS-LHJY', '广州市人力资源和社会保障局',
 '广州市"4050"人员灵活就业社保补贴', '广州市人力资源和社会保障局', '穗人社规〔2024〕5号', 'gov_doc'),
('GZ-GRAD-SUB-001', 'GZ-GRAD-SUB-2024', '440100', 'subsidy',
 ARRAY['flexible_employment'], '按实际缴纳社保费的50%给予补贴，最高不超过600元/月', 300, 600, 24,
 '2024-01-01', 0.87, 'verified', 1,
 '[{"name":"毕业年限","description":"离校2年内未就业高校毕业生","required":true},{"name":"灵活就业登记","description":"已办理灵活就业登记并缴纳社保","required":true,"tag_match":"flexible_employment"}]'::jsonb,
 '[{"name":"身份证","description":"本人身份证","source":"user","optional":false},{"name":"毕业证书","description":"高校毕业证书原件及复印件","source":"user","optional":false},{"name":"灵活就业证明","description":"街道出具的灵活就业证明","source":"gov","optional":false}]'::jsonb,
 'GZ-GOV-HRSS-LHJY', '广州市人力资源和社会保障局',
 '广州市高校毕业生灵活就业社保补贴', '广州市人力资源和社会保障局', '穗人社规〔2024〕7号', 'gov_doc')
ON CONFLICT (claim_id) DO NOTHING;
