package crawler

import (
	"fmt"
	"log"
	"net/url"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/proto"
)

type CDPVideoExtractor struct {
	browser       *rod.Browser
	mu            sync.Mutex
	chromePath    string
	pageTimeout   time.Duration
	cookieRefresh time.Time
}

func NewCDPVideoExtractor() *CDPVideoExtractor {
	return &CDPVideoExtractor{
		chromePath:  findChromeBinary(),
		pageTimeout: 30 * time.Second,
	}
}

func (e *CDPVideoExtractor) ensureBrowser() (*rod.Browser, error) {
	e.mu.Lock()
	defer e.mu.Unlock()

	if e.browser != nil {
		if _, err := e.browser.Pages(); err == nil {
			return e.browser, nil
		}
		log.Printf("[cdp] browser disconnected, reconnecting")
		e.browser.Close()
		e.browser = nil
	}

	bin := e.chromePath
	if bin == "" {
		return nil, fmt.Errorf("chrome binary not found")
	}

	u := launcher.New().
		Bin(bin).
		NoSandbox(true).
		Set("headless", "new").
		Set("disable-gpu").
		Set("disable-dev-shm-usage").
		Set("disable-background-networking").
		Set("disable-background-timer-throttling").
		Set("disable-renderer-backgrounding").
		Set("disable-blink-features", "AutomationControlled").
		Set("window-size", "1920,1080").
		Set("user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")
	launchURL, launchErr := u.Launch()
	if launchErr != nil {
		return nil, fmt.Errorf("launch chrome: %w", launchErr)
	}

	browser := rod.New().ControlURL(launchURL)
	if err := browser.Connect(); err != nil {
		return nil, fmt.Errorf("connect browser: %w", err)
	}
	e.browser = browser
	log.Printf("[cdp] browser connected")
	return browser, nil
}

func (e *CDPVideoExtractor) ExtractVideoURL(videoPageURL string) (string, error) {
	// Step 1: Refresh cookies from douyin.com if stale (every 10 min)
	if time.Since(e.cookieRefresh) > 10*time.Minute {
		cookiePath, err := e.refreshCookieFile()
		if err != nil {
			log.Printf("[cdp] cookie refresh failed: %v (yt-dlp may still have stale cookies)", err)
		} else {
			SetYtDlpCookiePath(cookiePath)
			e.cookieRefresh = time.Now()
			log.Printf("[cdp] fresh cookies written for yt-dlp: %s", cookiePath)
		}
	}

	// Step 2: Try direct API call using fresh cookies
	itemID := extractItemID(videoPageURL)
	if itemID == "" {
		return "", fmt.Errorf("cannot extract item ID from URL: %s", videoPageURL)
	}

	// Step 3: CDP failed to extract URL, return error so caller falls through to yt-dlp
	return "", fmt.Errorf("CDP used for cookie refresh only; use yt-dlp for actual extraction")
}

func (e *CDPVideoExtractor) refreshCookieFile() (string, error) {
	browser, err := e.ensureBrowser()
	if err != nil {
		return "", err
	}

	page, err := browser.Page(proto.TargetCreateTarget{})
	if err != nil {
		return "", fmt.Errorf("create page: %w", err)
	}
	defer page.Close()

	page = page.Timeout(e.pageTimeout)

	log.Printf("[cdp] visiting douyin.com to refresh cookies")
	if err := page.Navigate("https://www.douyin.com"); err != nil {
		return "", fmt.Errorf("navigate: %w", err)
	}
	if err := page.WaitLoad(); err != nil {
		return "", fmt.Errorf("wait load: %w", err)
	}
	time.Sleep(3 * time.Second)

	cookies, err := page.Cookies(nil)
	if err != nil {
		return "", fmt.Errorf("get cookies: %w", err)
	}

	// Build Netscape cookie file
	var sb strings.Builder
	sb.WriteString("# Netscape HTTP Cookie File\n")
	sb.WriteString("# Generated by NSIP CDP Video Extractor\n\n")

	now := time.Now()
	for _, c := range cookies {
		domain := c.Domain
		if domain == "" {
			domain = ".douyin.com"
		}

		domainFlag := "TRUE"
		// If domain doesn't start with ., it's a host-only cookie
		if !strings.HasPrefix(domain, ".") {
			domainFlag = "FALSE"
		}

		expires := int64(c.Expires)
		if expires <= 0 || c.Session {
			expires = now.Add(24 * time.Hour).Unix()
		}

		secure := "FALSE"
		if c.Secure {
			secure = "TRUE"
		}

		path := c.Path
		if path == "" {
			path = "/"
		}

		// URL-decode the value, then strip tabs (invalid in Netscape format)
		decodedValue, decErr := url.QueryUnescape(c.Value)
		value := strings.ReplaceAll(c.Value, "\t", " ")
		if decErr == nil {
			value = strings.ReplaceAll(decodedValue, "\t", " ")
		}

		// Netscape format: domain domain_flag path secure expires name value
		sb.WriteString(fmt.Sprintf("%s\t%s\t%s\t%s\t%d\t%s\t%s\n",
			domain, domainFlag, path, secure, expires, c.Name, value))
	}

	cookiePath := "/tmp/douyin_cookies.txt"
	if err := os.WriteFile(cookiePath, []byte(sb.String()), 0644); err != nil {
		return "", fmt.Errorf("write cookie file: %w", err)
	}

	log.Printf("[cdp] wrote %d cookies to %s", len(cookies), cookiePath)
	return cookiePath, nil
}

func extractItemID(url string) string {
	url = strings.TrimSpace(url)
	parts := strings.Split(url, "/")
	for i, p := range parts {
		if p == "video" && i+1 < len(parts) {
			id := parts[i+1]
			id = strings.Split(id, "?")[0]
			id = strings.Split(id, "#")[0]
			return id
		}
	}
	return ""
}

func (e *CDPVideoExtractor) Close() {
	e.mu.Lock()
	defer e.mu.Unlock()
	if e.browser != nil {
		e.browser.Close()
		e.browser = nil
	}
}
